# Generated by Django 4.2.3 on 2023-08-29 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_desciption_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
